//
//  File.swift
//  
//
//  Created by Andrew Rennard on 23/02/2021.
//

import Foundation

public enum WordType: String, CaseIterable {
    case accompaniment
    case antagonist
    case adventuretitlelocation
    case action
    case actionlocation
    case actionperson
    case actionidea
    case actionobject
    case adjective
    case age
    case animal
    case arablecrops
    case armour
    case aspect
    case bad
    case beerflavour
    case beertitle
    case bodypart
    case building
    case castleprefix
    case castlesuffix
    case castletitle
    case castlename
    case called
    case clothing
    case colour
    case consonant
    case construction
    case danger
    case dispersion
    case disposition
    case draw
    case drawspecial
    case dwarfname
    case dwarfprefix
    case dwarfsuffix
    case dungeonname
    case dungeonsuffix
    case dungeonprefix
    case dungeontitle
    case elfname
    case elfprefix
    case elfsuffix
    case element
    case entity
    case fame
    case farming
    case fieldcrops
    case fish
    case flavour
    case flavourdisposition
    case focus
    case fruit
    case gemstone
    case good
    case halflingname
    case halflingfirstnameprefix
    case halflingfirstnamesuffix
    case halflingsurnameprefix
    case halflingsurnamesuffix
    case humanname
    case humanprefix
    case humansuffix
    case infame
    case inns
    case ingredient
    case innfirstname
    case innsecondname
    case inhabitant
    case inntitle
    case landfeature
    case landscape
    case jewellery
    case journey
    case livestock
    case location
    case meat
    case magicaltreasure
    case magicbonus
    case mood
    case monster
    case musicalinstrument
    case noun
    case number
    case npc
    case object
    case oddity
    case ordinal
    case ore
    case orcname
    case orcsuffix
    case orcprefix
    case people
    case person
    case pie
    case place
    case placefeature
    case plothook
    case magic
    case preparation
    case quarry
    case race
    case ruler
    case sauce
    case sauceadjective
    case size
    case subject
    case surname
    case syllable
    case temperament
    case thing
    case treasure
    case treasureobject
    case treasurestate
    case unusualcrops
    case vegetable
    case village
    case villagename
    case villageindustry
    case villageprefix
    case villagesecond
    case villagesize
    case villagesuffix
    case villagetitle
    case vowel
    case waterfeature
    case weapon
    case yeolde
}
